
services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "80:8080"
      # - "443:8080" 

    environment:
      - PORT=8080
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=73UfQ8]rSt>S-(%h
      - DB_HOST=deloitte-vulnerable-bank.cenoq2e220za.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - vuln_network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=73UfQ8]rSt>S-(%h
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vuln_network

volumes:
  postgres_data:

networks:
  vuln_network:
    driver: bridge